#!/bin/bash

set -o errexit

echo 'Europe/Rome' > /etc/timezone
ln -sf /usr/share/zoneinfo/Europe/Rome /etc/localtime

echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen
echo 'it_IT.UTF-8 UTF-8' >> /etc/locale.gen
locale-gen 

apt-get update
apt-get install -y linux-image-cloud-amd64

echo "Please provide a password for the new host"
chroot ./a passwd root

