#!/bin/bash

set -o errexit

[[ -f ./new_host.cfg ]] || exit 0
source ./new_host.cfg

([[ -z $NEWHOST ]] || [[ -z $DISKSIZE ]] || [[ -z $SWAPSIZE ]]) && exit 1

[[ -b /dev/${KVMGROUP}/${NEWHOST} ]] && echo "EXISTS /dev/${KVMGROUP}/${NEWHOST}" && exit 1

apt-get install -y debootstrap rsync

echo "creating main /dev/${KVMGROUP}/${NEWHOST}"
lvcreate -n ${NEWHOST} -L ${DISKSIZE} $KVMGROUP && mkfs.ext4 /dev/${KVMGROUP}/${NEWHOST}
echo "creating swap /dev/${KVMGROUP}/${NEWHOST}"
lvcreate -n ${NEWHOST}-swap -L ${SWAPSIZE} $KVMGROUP && mkswap /dev/${KVMGROUP}/${NEWHOST}-swap

[[ -d ./a ]] || mkdir -v ./a
mount -v /dev/kvmgroup/${NEWHOST} ./a

# verify empty file system
[[ -d ./a/lost+found ]] || exit 1
[[ -d ./a/etc ]] && exit 1
[[ $(find ./a | wc -l) -gt 2 ]] && exit 1

debootstrap --include=vim,openssh-server,locales,bash-completion,lsof,rsync,dbus $DISTRIBUTION ./a

mkdir ./a/root/.ssh
chmod 700 ./a/root/.ssh/
rsync -av ~/.ssh/authorized_keys ./a/root/.ssh

chroot ./a ./chroot-script

umount a  

echo "<kernel>/var/lib/libvirt/images/vmlinuz-5.10.0-21-cloud-amd64</kernel>"
echo "<initrd>/var/lib/libvirt/images/initrd.img-5.10.0-21-cloud-amd64</initrd>"
echo "<cmdline>root=/dev/vda nohibernate noresume</cmdline>"

